### ISSUE TITLE
GOME 41 runtime slowly approaching its EOL

### ISSUE THREAD

**Issue by sophie-h** [flathub/com.bitstower.Markets#3]
Maybe it can be replaced with 42 already.

Version 43 should be available on 21. of this month.

**Comment by michalrujna** [comment]
Welcome,

On Fedora 37 fully updated, when I proceed with:

sudo flatpak update

terminal returns:

Info: runtime org.gnome.Platform branch 41 is end-of-life, with reason:
   The GNOME 41 runtime is no longer supported as of September 17, 2022. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   com.bitstower.Markets

I know U were working on this issue, however I'd like to inform U how it looks from a casual user perspective. I did not have a github user before writing this, just wanted to have everything nice and clean in my system after 'flatpak update'.

Cool piece of software, BTW! Bye.
